// ============================================================
// 📚 KAMUS KATA - File Perbendaharaan Kata
// Tambahkan kata baru di sini agar mudah diupdate!
// ============================================================

const WORD_BANK = {
  // ── Level 1: Huruf Tunggal ───────────────────────────────
  huruf: {
    label: "Huruf",
    icon: "🔤",
    color: "#FF6B9D",
    items: [
      { teks: "a", petunjuk: "huruf a kecil", emoji: "🍎" },
      { teks: "b", petunjuk: "huruf b kecil", emoji: "🦋" },
      { teks: "c", petunjuk: "huruf c kecil", emoji: "🐱" },
      { teks: "d", petunjuk: "huruf d kecil", emoji: "🐶" },
      { teks: "e", petunjuk: "huruf e kecil", emoji: "🐘" },
      { teks: "f", petunjuk: "huruf f kecil", emoji: "🐟" },
      { teks: "g", petunjuk: "huruf g kecil", emoji: "🦒" },
      { teks: "h", petunjuk: "huruf h kecil", emoji: "🐎" },
      { teks: "i", petunjuk: "huruf i kecil", emoji: "🦋" },
      { teks: "j", petunjuk: "huruf j kecil", emoji: "🦘" },
      { teks: "k", petunjuk: "huruf k kecil", emoji: "🐨" },
      { teks: "l", petunjuk: "huruf l kecil", emoji: "🦁" },
      { teks: "m", petunjuk: "huruf m kecil", emoji: "🐵" },
      { teks: "n", petunjuk: "huruf n kecil", emoji: "🦩" },
      { teks: "o", petunjuk: "huruf o kecil", emoji: "🦦" },
      { teks: "p", petunjuk: "huruf p kecil", emoji: "🐼" },
      { teks: "q", petunjuk: "huruf q kecil", emoji: "🦆" },
      { teks: "r", petunjuk: "huruf r kecil", emoji: "🐰" },
      { teks: "s", petunjuk: "huruf s kecil", emoji: "🐍" },
      { teks: "t", petunjuk: "huruf t kecil", emoji: "🐢" },
      { teks: "u", petunjuk: "huruf u kecil", emoji: "🦄" },
      { teks: "v", petunjuk: "huruf v kecil", emoji: "🦅" },
      { teks: "w", petunjuk: "huruf w kecil", emoji: "🐺" },
      { teks: "x", petunjuk: "huruf x kecil", emoji: "❌" },
      { teks: "y", petunjuk: "huruf y kecil", emoji: "🍋" },
      { teks: "z", petunjuk: "huruf z kecil", emoji: "🦓" },
      { teks: "A", petunjuk: "huruf A besar", emoji: "🍎" },
      { teks: "B", petunjuk: "huruf B besar", emoji: "🦋" },
      { teks: "C", petunjuk: "huruf C besar", emoji: "🐱" },
      { teks: "D", petunjuk: "huruf D besar", emoji: "🐶" },
      { teks: "E", petunjuk: "huruf E besar", emoji: "🐘" },
      { teks: "F", petunjuk: "huruf F besar", emoji: "🐟" },
      { teks: "G", petunjuk: "huruf G besar", emoji: "🦒" },
      { teks: "H", petunjuk: "huruf H besar", emoji: "🐎" },
      { teks: "I", petunjuk: "huruf I besar", emoji: "🦋" },
      { teks: "J", petunjuk: "huruf J besar", emoji: "🦘" },
      { teks: "K", petunjuk: "huruf K besar", emoji: "🐨" },
      { teks: "L", petunjuk: "huruf L besar", emoji: "🦁" },
      { teks: "M", petunjuk: "huruf M besar", emoji: "🐵" },
      { teks: "N", petunjuk: "huruf N besar", emoji: "🦩" },
      { teks: "O", petunjuk: "huruf O besar", emoji: "🦦" },
      { teks: "P", petunjuk: "huruf P besar", emoji: "🐼" },
      { teks: "Q", petunjuk: "huruf Q besar", emoji: "🦆" },
      { teks: "R", petunjuk: "huruf R besar", emoji: "🐰" },
      { teks: "S", petunjuk: "huruf S besar", emoji: "🐍" },
      { teks: "T", petunjuk: "huruf T besar", emoji: "🐢" },
      { teks: "U", petunjuk: "huruf U besar", emoji: "🦄" },
      { teks: "V", petunjuk: "huruf V besar", emoji: "🦅" },
      { teks: "W", petunjuk: "huruf W besar", emoji: "🐺" },
      { teks: "X", petunjuk: "huruf X besar", emoji: "⭐" },
      { teks: "Y", petunjuk: "huruf Y besar", emoji: "🍋" },
      { teks: "Z", petunjuk: "huruf Z besar", emoji: "🦓" },
    ],
  },

  // ── Level 2: Kata Sederhana ──────────────────────────────
  kata_mudah: {
    label: "Kata Mudah",
    icon: "🌟",
    color: "#FFB347",
    items: [
      { teks: "ibu", petunjuk: "orang yang melahirkan kita", emoji: "👩" },
      { teks: "ayah", petunjuk: "kepala keluarga", emoji: "👨" },
      { teks: "anak", petunjuk: "putra atau putri", emoji: "👧" },
      { teks: "kucing", petunjuk: "hewan peliharaan yang suka mengeong", emoji: "🐱" },
      { teks: "anjing", petunjuk: "hewan peliharaan yang suka menggonggong", emoji: "🐶" },
      { teks: "buku", petunjuk: "tempat kita membaca", emoji: "📚" },
      { teks: "meja", petunjuk: "tempat kita belajar", emoji: "🪑" },
      { teks: "nasi", petunjuk: "makanan pokok kita", emoji: "🍚" },
      { teks: "susu", petunjuk: "minuman dari sapi", emoji: "🥛" },
      { teks: "apel", petunjuk: "buah berwarna merah", emoji: "🍎" },
      { teks: "pisang", petunjuk: "buah berwarna kuning", emoji: "🍌" },
      { teks: "jeruk", petunjuk: "buah berwarna oranye", emoji: "🍊" },
      { teks: "bunga", petunjuk: "tanaman yang indah", emoji: "🌸" },
      { teks: "pohon", petunjuk: "tanaman besar di luar", emoji: "🌳" },
      { teks: "langit", petunjuk: "tempat awan berada", emoji: "☁️" },
      { teks: "hujan", petunjuk: "air yang jatuh dari langit", emoji: "🌧️" },
      { teks: "matahari", petunjuk: "bintang yang menyinari bumi", emoji: "☀️" },
      { teks: "bulan", petunjuk: "bersinar di malam hari", emoji: "🌙" },
      { teks: "bintang", petunjuk: "bercahaya di langit malam", emoji: "⭐" },
      { teks: "sekolah", petunjuk: "tempat kita belajar", emoji: "🏫" },
      { teks: "rumah", petunjuk: "tempat kita tinggal", emoji: "🏠" },
      { teks: "sepatu", petunjuk: "alas kaki kita", emoji: "👟" },
      { teks: "baju", petunjuk: "pakaian yang kita kenakan", emoji: "👕" },
      { teks: "tas", petunjuk: "tempat menaruh buku", emoji: "🎒" },
      { teks: "pensil", petunjuk: "alat untuk menulis", emoji: "✏️" },
      { teks: "crayon", petunjuk: "alat untuk mewarnai", emoji: "🖍️" },
      { teks: "gambar", petunjuk: "hasil karya melukis", emoji: "🎨" },
      { teks: "musik", petunjuk: "bunyi yang merdu", emoji: "🎵" },
      { teks: "bola", petunjuk: "dipakai untuk bermain", emoji: "⚽" },
      { teks: "boneka", petunjuk: "mainan berbentuk orang", emoji: "🪆" },
    ],
  },

  // ── Level 3: Kata Menengah ───────────────────────────────
  kata_sedang: {
    label: "Kata Sedang",
    icon: "🚀",
    color: "#6BCB77",
    items: [
      { teks: "Selamat", petunjuk: "ucapan saat senang", emoji: "🎉" },
      { teks: "Terima kasih", petunjuk: "ucapan rasa syukur", emoji: "🙏" },
      { teks: "Tolong", petunjuk: "kata meminta bantuan", emoji: "🤝" },
      { teks: "Maaf", petunjuk: "kata permohonan ampun", emoji: "😔" },
      { teks: "Baik", petunjuk: "lawan dari buruk", emoji: "👍" },
      { teks: "Senang", petunjuk: "perasaan gembira", emoji: "😄" },
      { teks: "Sedih", petunjuk: "perasaan tidak senang", emoji: "😢" },
      { teks: "Berani", petunjuk: "tidak takut", emoji: "💪" },
      { teks: "Jujur", petunjuk: "tidak bohong", emoji: "💎" },
      { teks: "Rajin", petunjuk: "suka bekerja keras", emoji: "📖" },
      { teks: "Pintar", petunjuk: "pandai belajar", emoji: "🧠" },
      { teks: "Cantik", petunjuk: "indah dan menarik", emoji: "🌺" },
      { teks: "Gagah", petunjuk: "tampan dan kuat", emoji: "🦸" },
      { teks: "Lucu", petunjuk: "membuat orang tertawa", emoji: "😂" },
      { teks: "Sayang", petunjuk: "rasa cinta kepada seseorang", emoji: "❤️" },
      { teks: "Bermain", petunjuk: "melakukan permainan", emoji: "🎮" },
      { teks: "Berlari", petunjuk: "bergerak cepat dengan kaki", emoji: "🏃" },
      { teks: "Bernyanyi", petunjuk: "melantunkan lagu", emoji: "🎤" },
      { teks: "Menari", petunjuk: "bergerak mengikuti musik", emoji: "💃" },
      { teks: "Memasak", petunjuk: "membuat makanan", emoji: "👨‍🍳" },
      { teks: "Membaca", petunjuk: "melihat dan memahami tulisan", emoji: "📚" },
      { teks: "Menulis", petunjuk: "membuat tulisan", emoji: "✍️" },
      { teks: "Melukis", petunjuk: "membuat gambar dengan cat", emoji: "🎨" },
      { teks: "Membantu", petunjuk: "ikut mengerjakan sesuatu", emoji: "🤲" },
      { teks: "Bersyukur", petunjuk: "berterima kasih atas nikmat", emoji: "🙏" },
      { teks: "Keluarga", petunjuk: "ayah, ibu, dan anak", emoji: "👨‍👩‍👧‍👦" },
      { teks: "Persahabatan", petunjuk: "hubungan antar teman", emoji: "🤜🤛" },
      { teks: "Indonesia", petunjuk: "negara kita tercinta", emoji: "🇮🇩" },
      { teks: "Pancasila", petunjuk: "dasar negara Indonesia", emoji: "⭐" },
      { teks: "Merah Putih", petunjuk: "bendera Indonesia", emoji: "🚩" },
    ],
  },

  // ── Level 4: Kalimat Pendek ──────────────────────────────
  kalimat: {
    label: "Kalimat",
    icon: "📝",
    color: "#C77DFF",
    items: [
      { teks: "Aku suka belajar.", petunjuk: "ungkapan suka belajar", emoji: "📚" },
      { teks: "Ibu memasak nasi.", petunjuk: "kegiatan ibu di dapur", emoji: "👩‍🍳" },
      { teks: "Ayah pergi kerja.", petunjuk: "kegiatan ayah setiap pagi", emoji: "💼" },
      { teks: "Kucing itu lucu.", petunjuk: "sifat hewan berbulu", emoji: "🐱" },
      { teks: "Aku makan nasi.", petunjuk: "kegiatan makan sehari-hari", emoji: "🍚" },
      { teks: "Buku ini tebal.", petunjuk: "menggambarkan buku banyak halaman", emoji: "📖" },
      { teks: "Langit berwarna biru.", petunjuk: "warna langit di siang hari", emoji: "🌤️" },
      { teks: "Hujan turun deras.", petunjuk: "cuaca saat hujan lebat", emoji: "🌧️" },
      { teks: "Bunga itu indah.", petunjuk: "kecantikan bunga di taman", emoji: "🌸" },
      { teks: "Aku suka bermain.", petunjuk: "kegiatan yang menyenangkan", emoji: "🎮" },
      { teks: "Tolong bantu aku.", petunjuk: "meminta pertolongan dengan sopan", emoji: "🤝" },
      { teks: "Terima kasih ya.", petunjuk: "ucapan rasa terima kasih", emoji: "😊" },
      { teks: "Selamat pagi semua.", petunjuk: "sapa saat pagi hari", emoji: "☀️" },
      { teks: "Ayo kita belajar.", petunjuk: "ajakan untuk belajar bersama", emoji: "✏️" },
      { teks: "Aku anak yang baik.", petunjuk: "sifat anak yang berperilaku baik", emoji: "😇" },
      { teks: "Mari bernyanyi bersama.", petunjuk: "ajakan bernyanyi bersama-sama", emoji: "🎵" },
      { teks: "Rajin pangkal pandai.", petunjuk: "pepatah tentang belajar", emoji: "🧠" },
      { teks: "Hemat pangkal kaya.", petunjuk: "pepatah tentang menabung", emoji: "🪙" },
      { teks: "Bersih itu sehat.", petunjuk: "pentingnya menjaga kebersihan", emoji: "🧼" },
      { teks: "Aku sayang keluarga.", petunjuk: "rasa cinta kepada keluarga", emoji: "❤️" },
    ],
  },
};

// ── Angka (bonus) ────────────────────────────────────────────
WORD_BANK.angka = {
  label: "Angka",
  icon: "🔢",
  color: "#4CC9F0",
  items: [
    { teks: "1", petunjuk: "angka satu", emoji: "1️⃣" },
    { teks: "2", petunjuk: "angka dua", emoji: "2️⃣" },
    { teks: "3", petunjuk: "angka tiga", emoji: "3️⃣" },
    { teks: "4", petunjuk: "angka empat", emoji: "4️⃣" },
    { teks: "5", petunjuk: "angka lima", emoji: "5️⃣" },
    { teks: "6", petunjuk: "angka enam", emoji: "6️⃣" },
    { teks: "7", petunjuk: "angka tujuh", emoji: "7️⃣" },
    { teks: "8", petunjuk: "angka delapan", emoji: "8️⃣" },
    { teks: "9", petunjuk: "angka sembilan", emoji: "9️⃣" },
    { teks: "10", petunjuk: "angka sepuluh", emoji: "🔟" },
    { teks: "11", petunjuk: "angka sebelas", emoji: "✨" },
    { teks: "12", petunjuk: "angka dua belas", emoji: "✨" },
    { teks: "20", petunjuk: "angka dua puluh", emoji: "✨" },
    { teks: "100", petunjuk: "angka seratus", emoji: "💯" },
  ],
};

// ── Export untuk dipakai di app.js ───────────────────────────
// Jika ingin menambah kategori baru, cukup tambahkan objek baru
// di WORD_BANK dengan format yang sama seperti di atas.
// Contoh:
// WORD_BANK.nama_kategori_baru = {
//   label: "Label Kategori",
//   icon: "🎯",
//   color: "#HEXCOLOR",
//   items: [
//     { teks: "kata", petunjuk: "keterangan kata", emoji: "🎯" },
//   ],
// };
